version: '3.4'
services:
  db:
    image: postgres

  super_graph:
    image: dosco/super-graph:latest
    environment:
      GO_ENV: "development"
    depends_on:
      - db
    ports:
      - "8080:8080"
    
  web:
    image: dosco/super-graph-demo:latest
    environment:
      RAILS_ENV: "development"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - super_graph